baseURL = 'https://www.alexstrong.design/'
languageCode = 'en-us'
title = 'The Big Walkabout'
theme = 'PaperMod'
canonifyURLs = true
relativeURLs = true

# SEO for web crawling
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    # SEO
    title = "The Big Walkabout | Alex Strong"
    description = "Documenting a bikepacking journey through the landscapes of New Zealand."
    keywords = ["New Zealand", "Bikepacking", "Photography", "Te Araroa", "Alex Strong", "Travel Blog", "Alex Strong Design"]
    author = "Alex Strong"

    # FAVICONS
    [params.assets]
      favicon = "favicon.ico"
      favicon16x16 = "favicon-16x16.png"
      favicon32x32 = "favicon-32x32.png"
      apple_touch_icon = "apple-touch-icon.png"
      safari_pinned_tab = "safari-pinned-tab.svg"
      android_chrome_192 = "android-chrome-192x192.png"
      android_chrome_512 = "android-chrome-512x512.png"

    # This ensures Android knows where to find your manifest
    manifest = "site.webmanifest"

    # This helps Google show your face or a logo in search results
    [params.images]
        url = "profile.jpg"

    defaultTheme = "auto"
    showCodeCopyButtons = true
    socialInHeader = true 

    # HOME INFO SECTION
    [params.homeInfoParams]
        Title = "Welcome to The Big Walkabout"
        Content = """
I'm bikepacking New Zealand.

Check out my [latest posts](/posts) or [subscribe](/subscribe) to get updates in your inbox.
"""

# SOCIAL ICONS
[[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[[params.socialIcons]]
    name = "email"
    url = "https://buttondown.email/AlexStrong"

# NAVIGATION MENU

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

[[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 15

[[menu.main]]
    identifier = "subscribe"
    name = "Newsletter"
    url = "/subscribe/"
    weight = 20

# IMAGE PROCESSING
[imaging]
    quality = 75
    resampleFilter = "CatmullRom"

# RSS SETTINGS
[rss]
    fullContent = true

# FOR FIXING AN IMAGE BUG
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

