baseURL = 'https://Alex-G-Strong.github.io/HugoBasedNZBlog/'
languageCode = 'en-us'
title = 'My NZ Blog'
theme = 'PaperMod'

[params]
    defaultTheme = "auto" # automatically switches between dark/light mode
    showCodeCopyButtons = true

[imaging]
  # Default JPEG quality
  quality = 75
  # Re-orient photos based on EXIF data (fixes sideways phone photos)
  resampleFilter = "CatmullRom"