baseURL = 'https://www.alexstrong.design/'
languageCode = 'en-us'
title = 'My NZ Blog'
theme = 'PaperMod'
canonifyURLs = true
relativeURLs = true

[params]
    defaultTheme = "auto" # automatically switches between dark/light mode
    showCodeCopyButtons = true

[imaging]
  # Default JPEG quality
  quality = 75
  # Re-orient photos based on EXIF data (fixes sideways phone photos)
  resampleFilter = "CatmullRom"

[[params.socialIcons]]
    name = "email"
    url = "https://buttondown.email/yourusername"

[rss]
  # This ensures the full text is available for Buttondown to grab
  fullContent = true